### ISSUE TITLE
Add additional clause for DestroyImmediate in GunFactory

### ISSUE THREAD

**Issue by Fueredoriku** [hackerspace-ntnu/Red-Planet-Rampage#205]
I think we should add an additional clause for the destroyImmediate `#if UNITY_EDITOR` check for destroyImmediate in GunFactory:
being in the gunTest scene, which I think is just about the only place we would need it for GUI-initialize gun button.

This change would remove the current error clutter of we get:
![image](https://github.com/hackerspace-ntnu/Prosjekt-Spill-H22/assets/54811121/ef76204e-a955-454d-8db0-806e7a553c88)

**Comment by toberge** [comment]
@Fueredoriku This isn't really relevant anymore right?

**Comment by Fueredoriku** [comment]
Agreed
