### ISSUE TITLE
Grand crevice modeling

### ISSUE THREAD

**Issue by CraZyB1336** [hackerspace-ntnu/Red-Planet-Rampage#237]
The context for GrandCanyon (name yet to be deciced) can be in the context of an old mining rig / society in a ravine, therefore some pathways might make sense and/or railways and some might be walkable. 
- [x] create props for level
- [x] railways / pathways
- [x] terrain

**Comment by toberge** [comment]
Completed in #571

**Comment by toberge** [comment]
Eller var dette den for nye-nye grand canyon 🤔
