### ISSUE TITLE
Fix mouse wiggling + soda popper weirdness

### ISSUE THREAD

**Issue by toberge** [hackerspace-ntnu/Red-Planet-Rampage#308]
Msg from Sondre:

> Tror det trengs en liten rework av muserotasjon -> spiller rotasjon. Slik det er nå er det noe jitter fra frame til frame som påvirker "stabiliteten" til ristingen. Med controller ser det ut til å funke bedre, men det er litt begrenset hvor godt en slik mattematisk modell kan funke med en jittery boundary. Man kan smoothe den tpå en del forskjellige måter i stedet for å ha en "sterk" boundary, dette vil hjelpe med jitteringen, men potensielt introdusere out of bounds problemer om den blir ristet "for hardt". Derfor tror jeg en litt smoothere implementasjon av muserotering er den beste løsningen.

**Comment by Fueredoriku** [comment]
Addressed by #394 and #398
