### ISSUE TITLE
Players can fly too high

### ISSUE THREAD

**Issue by toberge** [hackerspace-ntnu/Red-Planet-Rampage#311]
![image](https://github.com/hackerspace-ntnu/Prosjekt-Spill-H22/assets/44986729/cd614dc7-08e9-47e6-874e-15d38c6c75c7)

should we start limiting the knockback effect once you're past a certain height?

**Comment by Fueredoriku** [comment]
Canon flying is fixed in #310, but a ceiling height should definetly be put in place
