### ISSUE TITLE
Splash damage doesn't trigger onHit effects

### ISSUE THREAD

**Issue by Fueredoriku** [hackerspace-ntnu/Red-Planet-Rampage#350]
As an example: Hacking popups don't appear on explosion damage from cannon barrel

**Comment by toberge** [comment]
@Fueredoriku this ties into a major issue: We currently don't differentiate between on-hit effects that _should_ and _should not_ spread. Spawning hats and explosions are examples of non-spreading effects, while fire and hacking should spread through those effects.
