### ISSUE TITLE
Steam store elements

### ISSUE THREAD

**Issue by Fueredoriku** [hackerspace-ntnu/Red-Planet-Rampage#465]
- [ ] ![image](https://github.com/hackerspace-ntnu/Red-Planet-Rampage/assets/54811121/03288d6c-fd4d-4704-a86a-2f522b037920)
- [ ] ![image](https://github.com/hackerspace-ntnu/Red-Planet-Rampage/assets/54811121/16035571-03c0-412a-a0c3-1e73c3ed8fa4)
- [ ] ![image](https://github.com/hackerspace-ntnu/Red-Planet-Rampage/assets/54811121/0c361f37-f209-43b6-97a0-f7abfe543b9f)
- [ ] ![image](https://github.com/hackerspace-ntnu/Red-Planet-Rampage/assets/54811121/3e94d1ea-25d6-4b2f-a76b-b0ab4ad4d3cc)
- [ ] ![image](https://github.com/hackerspace-ntnu/Red-Planet-Rampage/assets/54811121/abc458c2-1bd4-4836-9088-5a2978b96f0c)
- [ ] ![image](https://github.com/hackerspace-ntnu/Red-Planet-Rampage/assets/54811121/151b564a-03d9-438b-a451-a3468b7daf06)

**Comment by CraZyB1336** [comment]
They should be in the google-drive under "Steam og Annet Assets"

**Comment by Fueredoriku** [comment]
Uploaded and waiting approval by Steam 👍
