### ISSUE TITLE
Noise texture for terrain on crater town 

### ISSUE THREAD

**Issue by Fueredoriku** [hackerspace-ntnu/Red-Planet-Rampage#518]
Should only have 3 tones per color, and not have visible tiling

**Comment by Fueredoriku** [comment]
An alternative could actually be to use "fake" round shadow directly underneath players (no matter the light direction), which is a very common design strategy used in 3D-platformers

**Comment by toberge** [comment]
Obligatory counter-argument about the possible necessity of having a ground texture regardless of the addition of a player shadow
