### ISSUE TITLE
Enlarger - Big-boy-bullet Extension

### ISSUE THREAD

**Issue by AleksandraGG** [hackerspace-ntnu/Red-Planet-Rampage#83]
**Hva den gjør:**

- Endrer size på bullets til store bullets
- Skyter en bullet om gangen
- Skyter bullets sakte?

**To-do:**

- [ ] Modellere

**Comment by AleksandraGG** [comment]
Progress so far:
<img width="615" alt="image" src="https://user-images.githubusercontent.com/115493724/219100279-d25315a3-caf8-4f6d-b506-e21f4aecd08a.png">

**Comment by ThomasJGabrielsen** [comment]
![Image](https://github.com/hackerspace-ntnu/Red-Planet-Rampage/assets/72146678/0f29f068-7a41-4cdc-a040-113e05c2c395)

Progress
