### ISSUE TITLE
New Player select menu

### ISSUE THREAD

**Issue by Fueredoriku** [hackerspace-ntnu/Red-Planet-Rampage#90]
- Players join a round table playing poker
  - Robots don't understand what they're doing, holds cards upside down and wrong direction
- 4 empty seats, A player pops into a chair when input is joined

**Comment by AleksandraGG** [comment]
<img width="356" alt="poker" src="https://github.com/hackerspace-ntnu/Prosjekt-Spill-H22/assets/115493724/0b3ec6fb-9d6c-4a4a-8c58-e72098f074e5">
