### ISSUE TITLE
Avoid rendering two cameras 💀 

### ISSUE THREAD

**Issue by toberge** [hackerspace-ntnu/Red-Planet-Rampage#908]
So what we need to do is:
- [ ] Disable player camera when viewing panning camera
- [ ] Disable panning camera when:
  - [ ] joining game with just one player
  - [ ] in splitscreen but noone has died yet
- at start of round the panning camera should be enabled; disable it when player is set up!

which means
- by default enabled
- disable panning cam when any player has their setplayerinput method called
- enable panning cam when player has died basically (could be more granular here)

Should result in a whopping **100%** performance increase.

Might resove #804 actually.

**Comment by Fueredoriku** [comment]
Casual 100% perfomance increase lmao
